const results = [
  {
    article_id: "34d3f85b062649b3ec369ad8f6d1114a",
    title:
      "San Jose’s Raging Waters park slated to make a comeback this summer",
    link: "https://www.mercurynews.com/2024/02/15/san-joses-raging-waters-park-slated-to-make-a-comeback-this-summer/",
    keywords: [
      "business",
      "california news",
      "entertainment",
      "features",
      "latest headlines",
      "local news",
      "news",
      "things to do",
      "around town",
      "news columnists",
      "parks",
      "san jose earthquakes",
      "theme parks",
    ],
    creator: ["Sal Pizarro"],
    video_url: null,
    description:
      "A new operator is expected to take over the Lake Cunningham Park attraction, which abruptly closed last September.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 22:07:12",
    image_url:
      "https://www.mercurynews.com/wp-content/uploads/2020/08/SJM-L-CLOCUNNINGHAM-0890-1.jpg?w=1400px&strip=all",
    source_id: "mercurynews",
    source_url: "https://www.mercurynews.com",
    source_icon: null,
    source_priority: 2968,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "1c12c19eb4dde22df2143eeda80e55fb",
    title:
      "San Jose’s Raging Waters park slated to make a comeback this summer",
    link: "https://www.eastbaytimes.com/2024/02/15/san-joses-raging-waters-park-slated-to-make-a-comeback-this-summer/",
    keywords: [
      "latest headlines",
      "around town",
      "news columnists",
      "parks",
      "theme parks",
    ],
    creator: ["Sal Pizarro"],
    video_url: null,
    description:
      "A new operator is expected to take over the Lake Cunningham Park attraction, which abruptly closed last September.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 22:07:12",
    image_url:
      "https://www.eastbaytimes.com/wp-content/uploads/2024/02/SJM-L-CLOCUNNINGHAM-0890-1-1.jpg?w=1400px&strip=all",
    source_id: "eastbaytimes",
    source_url: "https://www.eastbaytimes.com",
    source_icon: null,
    source_priority: 17164,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "53851a67a0f4885a26af3eccc1c5f828",
    title: "Rivian R2 Reveal Teaser Is Light On Detail But The Stakes Are High",
    link: "https://www.slashgear.com/1519246/rivian-r2-reveal-teaser-details/",
    keywords: ["electric vehicles", "news"],
    creator: ["staff@slashgear.com (Alex Hevesy)"],
    video_url: null,
    description:
      "Rivian has teased its upcoming R2 electric vehicle, showing off its silhouette paired with bright lights in a new video. What can fans expect from the EV?",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 22:06:15",
    image_url:
      "https://www.slashgear.com/img/gallery/rivian-r2-reveal-teaser-is-light-on-detail-but-the-stakes-are-high/l-intro-1708034550.jpg",
    source_id: "slashgear",
    source_url: "https://www.slashgear.com",
    source_icon:
      "https://ik.imagekit.io/plantoraImg/domain_icons/slashgear.png",
    source_priority: 10233,
    country: ["singapore", "united kingdom", "united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "506d0d3e30a3f553a0ed68f872cc3a89",
    title:
      "Florida woman arrested after allegedly slapping her mom in the face with grits over pizza argument",
    link: "https://www.foxnews.com/us/florida-woman-arrested-allegedly-slapping-mom-face-grits-pizza-argument",
    keywords: [
      "814295b1-e60d-5dd6-a2de-360b5e34d6d1",
      "fnc",
      "fox news",
      "fox-news/us/us-regions/southeast/florida",
      "fox-news/us/crime",
      "fox-news/us",
      "fox-news/food-drink/food",
      "fox-news/us",
      "article",
    ],
    creator: null,
    video_url: null,
    description:
      "A 28-year-old Florida woman was arrested after she allegedly smacked her mom in the face with grits during an argument about pizza.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 22:00:33",
    image_url:
      "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2024/02/931/523/Jakiela-Mobley.jpg?ve=1&tl=1",
    source_id: "foxnews",
    source_url: "https://www.foxnews.com",
    source_icon: "https://ik.imagekit.io/plantoraImg/domain_icons/foxnews.jpg",
    source_priority: 59,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "94f1c51545aa2c78b5750084b92c3e00",
    title:
      "Flor de Feria 2024 vuelve a Planta Uno: cuándo y que se puede encontrar",
    link: "https://www.elsol.com.ar/departamentales/flor-de-feria-2024-vuelve-a-planta-uno-cuando-y-que-se-puede-encontrar/",
    keywords: ["departamentales", "feria", "moda circular", "planta uno"],
    creator: ["El Sol"],
    video_url: null,
    description:
      "“Flor de Feria” vuelve al complejo gastronómico Planta Uno con una propuesta que ofrece diseño, gastronomía y entretenimiento. Se realizará los días 17 y 18 de febrero, de las 18 hasta las 00. La entrada es libre y gratuita, y se invita a colaborar donando alimentos para Fundavita y Banco de Alimentos Mendoza. La feria […] The post Flor de Feria 2024 vuelve a Planta Uno: cuándo y que se puede encontrar appeared first on Diario El Sol Mendoza.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 22:00:15",
    image_url:
      "https://i0.wp.com/newspack-elsol.s3.amazonaws.com/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-15-at-17.25.13.jpeg?fit=768%2C551&ssl=1",
    source_id: "elsol",
    source_url: "https://www.elsol.com.ar",
    source_icon: "https://ik.imagekit.io/plantoraImg/domain_icons/elsol.png",
    source_priority: 502049,
    country: ["argentina"],
    category: ["business"],
    language: "spanish",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "56ba911640ef2c686eac67094832720e",
    title:
      "¿Estás en Las Grutas y no tenés plan? A 15 km, en San Antonio, hay lugares, playas y museos para descubrir",
    link: "https://www.rionegro.com.ar/sociedad/voy-turismo/estas-en-las-grutas-y-no-tenes-plan-a-15-km-en-san-antonio-hay-lugares-playas-y-museos-para-descubrir-3419397/",
    keywords: [
      "sociedad",
      "voy turismo en la patagonia",
      "las grutas",
      "san antonio oeste",
      "temporada 2024",
      "turismo",
      "verano 2024",
    ],
    creator: ["Vanesa Miyar"],
    video_url: null,
    description:
      "San Antonio Oeste, la ciudad costera que está ubicada a 15 km de Las Grutas, es una buena opción para visitar y descubrir lugares únicos. En ella no sólo hay playas tranquilas y agrestes sino sitios distintos con buena gastronomía. Otro de sus atractivos es el pasado de la región, ligado a la historia del […]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 22:00:00",
    image_url:
      "https://www.rionegro.com.ar/wp-content/uploads/2024/02/marea-1.jpg?w=215&h=120",
    source_id: "rionegro",
    source_url: "https://www.rionegro.com.ar",
    source_icon: "https://ik.imagekit.io/plantoraImg/domain_icons/rionegro.png",
    source_priority: 337049,
    country: ["argentina"],
    category: ["top"],
    language: "spanish",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "05e5401f4b9b715635ccd150f3e7f5ee",
    title:
      "Rathaus Galerie Essen: Gastro-Betreiber erheben schwere Vorwürfe – „Würde hier auch nicht essen gehen“",
    link: "https://www.derwesten.de/staedte/essen/rathaus-galerie-essen-food-court-doener-pizza-schnitzel-f-id300831791.html",
    keywords: ["essen"],
    creator: null,
    video_url: null,
    description:
      "In der Rathaus Galerie Essen sorgt ein Dauer-Problem für Frust bei den Gastro-Betreibern. Jetzt spricht der Eigentümer Klartext.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 21:59:14",
    image_url:
      "https://www.derwesten.de/wp-content/uploads/sites/8/2024/02/imago0198481989h-e1707403726892.jpg?w=1200&h=800&crop=1",
    source_id: "derwesten",
    source_url: "https://www.derwesten.de",
    source_icon:
      "https://ik.imagekit.io/plantoraImg/domain_icons/derwesten.png",
    source_priority: 1887680,
    country: ["germany"],
    category: ["top"],
    language: "german",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "3c79f5102924973d6115dfced1c7be34",
    title:
      "Franklin from 'Peanuts' gets to shine in the spotlight of a new animated Apple TV+ special",
    link: "https://japantoday.com/category/entertainment/franklin-from-%27peanuts%27-gets-to-shine-in-the-spotlight-of-a-new-animated-apple-tv-special",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "The mild-mannered Franklin — the first Black character in the “Peanuts” comic strip — gets to shine in his own animated Apple TV+ special this month in a…",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 21:39:16",
    image_url:
      "https://japantoday-asset.scdn3.secure.raxcdn.com/img/store/f6/e9/f649c92d4c6c93d29b7f85f8588e3ae12247/download/_w850.jpg",
    source_id: "japantoday",
    source_url: "https://japantoday.com",
    source_icon:
      "https://ik.imagekit.io/plantoraImg/domain_icons/japantoday.png",
    source_priority: 27031,
    country: ["japan"],
    category: ["entertainment"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "91163fb508e467010ccceea8daceb1da",
    title:
      "“Tiene un maní en el cerebro”, destruyen a Kendall Jenner por promover su marca de tequila a estudiantes",
    link: "https://www.publimetro.cl/entretenimiento/2024/02/15/tiene-un-mani-en-el-cerebro-destruyen-a-kendall-jenner-por-promover-su-marca-de-tequila-a-estudiantes/",
    keywords: null,
    creator: ["Roxana Peña"],
    video_url: null,
    description:
      "Kendall Jenner desató la ira de los usuarios en redes por promover su marca de tequila en universidades y se le fueron encima",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 21:35:31",
    image_url:
      "https://www.publimetro.cl/resizer/LTr9AqfvLtucghTVjJ-g_M-BgEc=/cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/63NTMCHCQFANJNU2QFMQFIFAME.jpg",
    source_id: "biobiochile",
    source_url: "https://www.biobiochile.cl",
    source_icon:
      "https://ik.imagekit.io/plantoraImg/domain_icons/biobiochile.png",
    source_priority: 89186,
    country: ["chile"],
    category: ["top"],
    language: "spanish",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
  {
    article_id: "ad9decf2c842d2b01bf588eb1f73a668",
    title:
      "Si eres un amante de las pizzas, no te pierdas las promociones especiales de Servipizza para cada día de la semana",
    link: "https://www.informacion.es/ocio/gastronomia/2024/02/15/servipizza-sabor-artesano-delicioso-provincia-obrador-98209588.html",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Si la experiencia es un grado, Servipizza tiene cum laude en su tesis doctoral. Y es que son un grupo de restauración que lleva más de treinta años especializados en la elaboración de pizzas y otros productos.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-02-15 21:30:25",
    image_url:
      "https://estaticos-cdn.prensaiberica.es/clip/ecd31cbc-d3fe-4bcb-bdee-9f910bdb689d_16-9-aspect-ratio_default_0.jpg",
    source_id: "diarioinformacion",
    source_url: "http://www.diarioinformacion.com",
    source_icon:
      "https://ik.imagekit.io/plantoraImg/domain_icons/diarioinformacion.png",
    source_priority: 2081549,
    country: ["spain"],
    category: ["top"],
    language: "spanish",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
  },
];
